repositories:
  remote:
   - https://stocksoftware.jfrog.io/stocksoftware/maven2
   - https://repo.maven.apache.org/maven2
   - https://stocksoftware.jfrog.io/stocksoftware/staging

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.14

  shade_task: org.realityforge.ant.shade:ant-shade-task:jar:0.1

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.1

  javapoet: com.squareup:javapoet:jar:1.12.0

  proton_core: org.realityforge.proton:proton-core:jar:0.38
  proton_qa: org.realityforge.proton:proton-qa:jar:0.38

  compile_testing: com.google.testing.compile:compile-testing:jar:0.18-rf
  guava: com.google.guava:guava:jar:27.1-jre
  guava_failureaccess: com.google.guava:failureaccess:jar:1.0.1
  truth: com.google.truth:truth:jar:0.45
  junit: junit:junit:jar:4.12
  hamcrest_core: org.hamcrest:hamcrest-core:jar:1.3

  javax_json: org.glassfish:javax.json:jar:1.1

  mockito: org.mockito:mockito-all:jar:1.10.19

  gir: org.realityforge.gir:gir-core:jar:0.11

  revapi_diff: org.realityforge.revapi.diff:revapi-diff:jar:all:0.08

  # GWT deps
  gwt_user: org.realityforge.com.google.gwt:gwt-user:jar:2.8.2-v20191108
  gwt_dev: org.realityforge.com.google.gwt:gwt-dev:jar:2.8.2-v20191108

  javaee_api: javax:javaee-api:jar:8.0.1
