repositories:
  remote:
   - https://repo.maven.apache.org/maven2
   - https://stocksoftware.artifactoryonline.com/stocksoftware/public
   - https://stocksoftware.artifactoryonline.com/stocksoftware/oss
   - https://stocksoftware.artifactoryonline.com/stocksoftware/staging

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.14

  shade_task: org.realityforge.ant.shade:ant-shade-task:jar:0.1

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.1

  javax_inject: javax.inject:javax.inject:jar:1

  jetbrains_annotations: org.realityforge.org.jetbrains.annotations:org.jetbrains.annotations:jar:1.2.0

  guiceyloops: org.realityforge.guiceyloops:guiceyloops:jar:0.102

  autocommon: com.google.auto:auto-common:jar:0.10
  javapoet: com.squareup:javapoet:jar:1.11.1
  guava: com.google.guava:guava:jar:25.0-jre

  proton_core: org.realityforge.proton:proton-core:jar:0.07
  proton_qa: org.realityforge.proton:proton-qa:jar:0.07

  compile_testing: com.google.testing.compile:compile-testing:jar:0.15
  truth: com.google.truth:truth:jar:0.39
  junit: junit:junit:jar:4.12
  hamcrest_core: org.hamcrest:hamcrest-core:jar:1.3
